# Generated by Django 3.1.3 on 2020-11-26 19:49

import codenames.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('room', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('date', models.DateField(null=True)),
                ('place', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B')], default=('A', 'A'), max_length=1)),
                ('dummy', models.BooleanField(default=False)),
                ('cup', models.ForeignKey(default=codenames.models.get_current_cup_id, on_delete=django.db.models.deletion.CASCADE, related_name='groupcup', to='codenames.cup')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dummy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=2)),
                ('_description', models.CharField(max_length=30)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_home_win', models.BooleanField(default=True)),
                ('_auto_score', models.IntegerField(blank=True, choices=[(-9, '0:9'), (-8, '0:8'), (-7, '0:7'), (-6, '0:6'), (-5, '0:5'), (-4, '0:4'), (-3, '0:3'), (-2, '0:2'), (-1, '0:1'), (0, '0:0'), (1, '1:0'), (2, '2:0'), (3, '3:0'), (4, '4:0'), (5, '5:0'), (6, '6:0'), (7, '7:0'), (8, '8:0')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('has_come', models.BooleanField(blank=True, default=False, null=True)),
                ('seed', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True)),
                ('fee_size', models.IntegerField(choices=[(700, 700), (900, 900)], default=700)),
                ('dummy', models.BooleanField(default=False)),
                ('cup', models.ForeignKey(default=codenames.models.get_current_cup_id, on_delete=django.db.models.deletion.CASCADE, related_name='teamcup', to='codenames.cup')),
                ('first_player', models.ForeignKey(default=codenames.models.get_dummy_player_id, on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='codenames.player')),
                ('group', models.ForeignKey(default=codenames.models.get_dummy_group_id, on_delete=django.db.models.deletion.CASCADE, related_name='teamgroup', to='codenames.group')),
                ('second_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='codenames.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('score', models.IntegerField(choices=[(-9, '0:9'), (-8, '0:8'), (-7, '0:7'), (-6, '0:6'), (-5, '0:5'), (-4, '0:4'), (-3, '0:3'), (-2, '0:2'), (-1, '0:1'), (0, '0:0'), (1, '1:0'), (2, '2:0'), (3, '3:0'), (4, '4:0'), (5, '5:0'), (6, '6:0'), (7, '7:0'), (8, '8:0')], default=0)),
                ('arena', models.ForeignKey(default=codenames.models.get_dummy_arena_id, on_delete=django.db.models.deletion.CASCADE, related_name='arena', to='codenames.arena')),
                ('away_team', models.ForeignKey(default=codenames.models.get_dummy_team_id, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='codenames.team')),
                ('group', models.ForeignKey(default=codenames.models.get_dummy_group_id, on_delete=django.db.models.deletion.CASCADE, related_name='gameresultgroup', to='codenames.group')),
                ('home_team', models.ForeignKey(default=codenames.models.get_dummy_team_id, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='codenames.team')),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_type', to='codenames.resulttype')),
            ],
        ),
        migrations.AddField(
            model_name='arena',
            name='group',
            field=models.ForeignKey(default=codenames.models.get_dummy_group_id, on_delete=django.db.models.deletion.CASCADE, related_name='arenagroup', to='codenames.group'),
        ),
    ]
