# Generated by Django 3.1.3 on 2020-11-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
