# Generated by Django 3.1.3 on 2020-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='room',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
