# Generated by Django 3.1.3 on 2020-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0002_arena_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
