# Generated by Django 3.1.3 on 2020-11-27 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0002_arena_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='away_team_fouls',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='home_team_fouls',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
