# Generated by Django 3.1.3 on 2020-11-25 23:38

import codenames.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_auto_20201125_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cup_id',
            field=models.ForeignKey(default=codenames.models.get_current_cup_id, on_delete=django.db.models.deletion.CASCADE, related_name='teamcup_id', to='codenames.group'),
        ),
    ]
