# Generated by Django 3.1.3 on 2020-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0004_auto_20201211_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttype',
            name='do_delete',
            field=models.BooleanField(default=False),
        ),
    ]
