# Generated by Django 3.1.3 on 2020-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0005_resulttype_do_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=6),
        ),
    ]
