# Generated by Django 3.1.3 on 2020-11-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0005_auto_20201126_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='cup_id',
        ),
    ]
