# Generated by Django 3.1.3 on 2020-11-25 23:48

import codenames.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0006_remove_team_cup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cup_id',
            field=models.ForeignKey(default=codenames.models.get_current_cup_id, on_delete=django.db.models.deletion.CASCADE, related_name='groupcup_id', to='codenames.cup'),
        ),
    ]
